module.exports = (sequelize, type) => {
  return sequelize.define("post", {
    id: {
      type: type.BIGINT,
      primaryKey: true,
      autoIncrement: true,
    },
    service: type.STRING,
    price: type.STRING,
    itemQuantity: type.STRING,
    itemSize: type.STRING,
    itemDescription: type.TEXT,
    packerDescription: type.TEXT,
    cleanerDescription: type.TEXT,
    residenceType: type.STRING,
    cleaningType: type.STRING,
    squareMetres: type.STRING,
    iHaveCleaningSupplies: type.BOOLEAN,
    iHavePackingSupplies: type.BOOLEAN,
    date: type.STRING,
    startTime: type.STRING,
    endTime: type.STRING,
    handymanStartTime: type.STRING,
    handymanEndTime: type.STRING,
    packerStartTime: type.STRING,
    packerEndTime: type.STRING,
    cleanerStartTime: type.STRING,
    cleanerEndTime: type.STRING,
    pLocation: type.STRING,
    dLocation: type.STRING,
    handymanLocation: type.STRING,
    packerLocation: type.STRING,
    cleanerLocation: type.STRING,
    packersRequired: type.BOOLEAN,
    handymanRequired: type.BOOLEAN,
    cleanersRequired: type.BOOLEAN,
    handymanQuantity: type.STRING,
    handymanPrice: type.STRING,
    packerQuantity: type.STRING,
    packerPrice: type.STRING,
    cleanerQuantity: type.STRING,
    cleanerPrice: type.STRING,
    vehicleSize: type.STRING,
    images: type.TEXT,
    loadedCarImages: type.TEXT,
    loadedCarImagesApproved: type.BOOLEAN,
    finalImages: type.TEXT,
    finalImagesApproved: type.BOOLEAN,
    userfcm:type.STRING,
    helperfcm:type.STRING,
    israte: {type:type.BOOLEAN,defaultValue:false},
    status: {
      type: type.STRING,
      defaultValue: "In Review",
    },
    location: type.GEOMETRY('POINT'),
  });
};